import Link from "next/link";
import { CalendarDays, HelpCircle, MessageSquare, Bell, Plug } from "lucide-react";
import { Card } from "@/components/ui";
import { requireUser } from "@/lib/auth";
import { requireTeamAccess } from "@/lib/permissions";
import { getActiveGameForTeam } from "@/lib/data";
import { PageHeader } from "@/components/page-header";
const links = [["Game details","game",CalendarDays],["FAQs","faqs",HelpCircle],["Messages","messages",MessageSquare],["Reminders","reminders",Bell],["GroupMe","integrations/groupme",Plug]] as const;
export default async function TeamHome({ params }: { params: Promise<{ teamId: string }> }) { const { teamId } = await params; const { supabase, user } = await requireUser(); const { team } = await requireTeamAccess(supabase, user.id, teamId); const game = await getActiveGameForTeam(supabase, teamId); return <div><PageHeader title={team.name} subtitle={game ? `This week's game: ${game.opponent} on ${game.game_date}` : "No game posted yet. Add this week's game so families can get instant answers."} action={<Link href={`/app/team/${teamId}/game`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#F2A341] px-4 py-2.5 text-base font-semibold text-slate-900 shadow-sm transition hover:bg-[#E89A30]">+ New Game</Link>} className="sticky top-[73px] z-10 rounded-xl border border-[#E5E7EB] bg-white px-4 py-4 shadow-sm" /><div className="mt-8 grid gap-4 md:grid-cols-3">{links.map(([title, href, Icon]) => <Link key={href} href={`/app/team/${teamId}/${href}`}><Card className="h-full transition hover:-translate-y-0.5 hover:shadow-md"><Icon className="h-8 w-8 text-[#0C2D5A]" /><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mt-2 text-base text-slate-600">Open {title.toLowerCase()}.</p></Card></Link>)}</div></div>; }
