create extension if not exists "pgcrypto";

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, created_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, sport text not null default 'baseball', owner_user_id uuid not null references auth.users(id) on delete restrict, plan text not null default 'free' check (plan in ('free','coach_pro','club_pro')), is_active boolean not null default true, created_at timestamptz not null default now());
create table public.organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check (role in ('owner','admin','coach')), created_at timestamptz not null default now(), unique (organization_id, user_id));
create table public.teams (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, age_group text, season text, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.groupme_connections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade, platform text not null default 'groupme', group_id text not null unique, bot_id text, bot_name text, access_token_encrypted text, callback_url text, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.games (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade, opponent text not null, game_date date not null, game_time text, arrival_time text, location_name text, location_address text, google_maps_url text, home_or_away text check (home_or_away is null or home_or_away in ('home','away','neutral')), uniform text, what_to_bring text, parking_notes text, additional_notes text, status text not null default 'scheduled', is_active boolean not null default true, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.faqs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade, keyword text, question text not null, answer text not null, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now());
create table public.message_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade, groupme_connection_id uuid references public.groupme_connections(id) on delete set null, sender_name text, sender_user_id text, question text not null, detected_intents jsonb, answer text, needs_followup boolean not null default false, raw_payload jsonb, created_at timestamptz not null default now());
create table public.reminder_rules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade unique, enabled boolean not null default true, send_24h_before boolean not null default true, send_2h_before boolean not null default true, custom_offsets jsonb, created_at timestamptz not null default now());
create table public.reminder_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade, game_id uuid not null references public.games(id) on delete cascade, reminder_type text not null, sent_at timestamptz not null default now(), status text not null, payload jsonb, unique (game_id, reminder_type));
create table public.subscriptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade unique, provider text not null default 'stripe', external_customer_id text, external_subscription_id text, plan text, status text, current_period_end timestamptz, created_at timestamptz not null default now());
create table public.usage_counters (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, metric text not null, period_start date not null, period_end date not null, count integer not null default 0, unique (organization_id, metric, period_start));

create index on public.organization_members(user_id); create index on public.teams(organization_id); create index on public.games(team_id, is_active, game_date); create index on public.faqs(team_id); create index on public.message_logs(team_id, created_at desc); create index on public.groupme_connections(group_id);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger games_touch_updated_at before update on public.games for each row execute function public.touch_updated_at();
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, email) values (new.id, new.raw_user_meta_data->>'full_name', new.email) on conflict (id) do update set email = excluded.email; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.is_org_member(org_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.organization_members m where m.organization_id = org_id and m.user_id = auth.uid()); $$;
create or replace function public.is_org_admin(org_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.organization_members m where m.organization_id = org_id and m.user_id = auth.uid() and m.role in ('owner','admin')); $$;

alter table public.profiles enable row level security; alter table public.organizations enable row level security; alter table public.organization_members enable row level security; alter table public.teams enable row level security; alter table public.groupme_connections enable row level security; alter table public.games enable row level security; alter table public.faqs enable row level security; alter table public.message_logs enable row level security; alter table public.reminder_rules enable row level security; alter table public.reminder_logs enable row level security; alter table public.subscriptions enable row level security; alter table public.usage_counters enable row level security;
create policy "profiles self read" on public.profiles for select using (id = auth.uid()); create policy "profiles self update" on public.profiles for update using (id = auth.uid()); create policy "profiles self insert" on public.profiles for insert with check (id = auth.uid());
create policy "org member read" on public.organizations for select using (public.is_org_member(id)); create policy "org owner insert" on public.organizations for insert with check (owner_user_id = auth.uid()); create policy "org admin update" on public.organizations for update using (public.is_org_admin(id));
create policy "members read org" on public.organization_members for select using (public.is_org_member(organization_id)); create policy "members self bootstrap" on public.organization_members for insert with check (user_id = auth.uid() and exists (select 1 from public.organizations o where o.id = organization_id and o.owner_user_id = auth.uid())); create policy "members admin manage" on public.organization_members for all using (public.is_org_admin(organization_id)) with check (public.is_org_admin(organization_id));
create policy "teams member read" on public.teams for select using (public.is_org_member(organization_id)); create policy "teams member write" on public.teams for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create policy "groupme member read" on public.groupme_connections for select using (public.is_org_member(organization_id)); create policy "groupme member write" on public.groupme_connections for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create policy "games member read" on public.games for select using (public.is_org_member(organization_id)); create policy "games member write" on public.games for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create policy "faqs member read" on public.faqs for select using (public.is_org_member(organization_id)); create policy "faqs member write" on public.faqs for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create policy "logs member read" on public.message_logs for select using (public.is_org_member(organization_id)); create policy "logs service insert" on public.message_logs for insert with check (true);
create policy "rules member read" on public.reminder_rules for select using (public.is_org_member(organization_id)); create policy "rules member write" on public.reminder_rules for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create policy "reminder logs member read" on public.reminder_logs for select using (public.is_org_member(organization_id)); create policy "reminder logs service insert" on public.reminder_logs for insert with check (true);
create policy "subscriptions admin read" on public.subscriptions for select using (public.is_org_admin(organization_id)); create policy "usage member read" on public.usage_counters for select using (public.is_org_member(organization_id)); create policy "usage service insert" on public.usage_counters for insert with check (true); create policy "usage service update" on public.usage_counters for update using (true);
