import { Bot, CalendarDays, MessageCircle, ShieldCheck } from "lucide-react";
import { LinkButton, Card } from "@/components/ui";
import { PLANS } from "@/lib/billing";
const features = [
  { icon: MessageCircle, title: "Your team's chat, handled", body: "Parents ask in GroupMe and get quick answers from the game info you already posted." },
  { icon: CalendarDays, title: "One place for game day", body: "Keep date, arrival time, location, uniforms, and notes clear for every family." },
  { icon: ShieldCheck, title: "Every team stays organized", body: "Built so each team's details stay cleanly separated in one place." },
  { icon: Bot, title: "Coach-friendly AI", body: "CoachAssist only uses your posted facts and flags anything that still needs a coach update." },
];
export default function LandingPage() { return <main className="min-h-screen bg-gradient-to-b from-[#0C2D5A] via-[#103A75] to-slate-100 text-white"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><div className="text-xl font-black">CoachAssist</div><div className="flex gap-3 text-sm"><a href="/pricing" className="py-2 text-blue-100">Pricing</a><LinkButton href="/login" className="bg-white text-[#0C2D5A] hover:bg-blue-50">Log in</LinkButton></div></nav><section className="mx-auto max-w-6xl px-6 py-16 md:py-20"><div className="max-w-3xl"><p className="font-semibold text-blue-200">Built for busy youth sports coaches.</p><h1 className="mt-4 text-4xl font-black tracking-tight md:text-7xl">Run your team updates without the chaos.</h1><p className="mt-6 text-lg text-blue-100 md:text-xl">CoachAssist connects your schedule and team notes to GroupMe so families always know when to arrive, where to go, and what to bring.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/signup" className="bg-white text-[#0C2D5A] hover:bg-blue-50">Start free</LinkButton><LinkButton href="/pricing" className="bg-[#F2A341] text-slate-900 hover:bg-[#E89A30]">View plans</LinkButton></div></div></section><section className="bg-slate-100 px-6 py-16 text-slate-900"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-4">{features.map((f) => <Card key={f.title}><f.icon className="h-8 w-8 text-[#0C2D5A]" /><h3 className="mt-4 text-lg font-bold">{f.title}</h3><p className="mt-2 text-base text-slate-600">{f.body}</p></Card>)}</div><div className="mx-auto mt-12 grid max-w-6xl gap-5 md:grid-cols-3">{Object.values(PLANS).map((plan) => <Card key={plan.id}><h3 className="text-xl font-bold">{plan.name}</h3><p className="mt-2 text-3xl font-black">{plan.monthlyPrice}<span className="text-sm font-medium text-slate-500">/mo</span></p><ul className="mt-4 space-y-2 text-sm text-slate-600">{plan.features.map((feature) => <li key={feature}>- {feature}</li>)}</ul></Card>)}</div></section></main>; }
