import Link from "next/link";
import type { Route } from "next";
import { cn } from "@/lib/utils";
import type { ReactNode } from "react";
export function Button({ children, className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={cn("inline-flex items-center justify-center rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-800 disabled:opacity-50", className)} {...props}>{children}</button>; }
export function LinkButton({ children, href, className }: { children: ReactNode; href: Route; className?: string }) { return <Link href={href} className={cn("inline-flex items-center justify-center rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-800", className)}>{children}</Link>; }
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("rounded-2xl border border-slate-200 bg-white p-6 shadow-sm", className)}>{children}</div>; }
export function Field({ label, name, type = "text", defaultValue, placeholder, required, multiline }: { label: string; name: string; type?: string; defaultValue?: string | null; placeholder?: string; required?: boolean; multiline?: boolean }) { const base = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none ring-blue-200 focus:ring-4"; return <label className="block text-sm font-medium text-slate-700"><span>{label}</span>{multiline ? <textarea name={name} defaultValue={defaultValue || ""} placeholder={placeholder} required={required} className={cn(base, "min-h-24")} /> : <input name={name} type={type} defaultValue={defaultValue || ""} placeholder={placeholder} required={required} className={base} />}</label>; }
export function EmptyState({ title, body, action }: { title: string; body: string; action?: ReactNode }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><h3 className="text-lg font-semibold text-slate-900">{title}</h3><p className="mt-2 text-sm text-slate-600">{body}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
export function Badge({ children, tone = "blue" }: { children: ReactNode; tone?: "blue" | "green" | "amber" | "slate" }) { const tones = { blue:"bg-blue-50 text-blue-700", green:"bg-emerald-50 text-emerald-700", amber:"bg-amber-50 text-amber-700", slate:"bg-slate-100 text-slate-700" }; return <span className={cn("rounded-full px-2.5 py-1 text-xs font-semibold", tones[tone])}>{children}</span>; }
