import OpenAI from "openai";
import { z } from "zod";
import type { Tables } from "@/types/database";

export const intents = ["game_time","arrival_time","game_date","game_location","directions","parking","uniform","what_to_bring","opponent","weather","cancellation","faq_general","greeting","unknown"] as const;
export const aiAnswerSchema = z.object({ intents: z.array(z.enum(intents)).default(["unknown"]), answer: z.string(), followups: z.array(z.string()).max(3).default([]), needsFollowup: z.boolean().default(false) });
export type AiAnswer = z.infer<typeof aiAnswerSchema>;
export type TeamContext = { organizationName: string; teamName: string; game: Tables<"games"> | null; faqs: Array<Pick<Tables<"faqs">, "keyword" | "question" | "answer">> };
function suggestFollowups(found: string[]) { if (found.includes("game_time") || found.includes("arrival_time")) return ["Where is the field?", "What uniform should players wear?"]; if (found.includes("game_location") || found.includes("directions")) return ["Any parking notes?", "What time should we arrive?"]; if (found.includes("uniform")) return ["What should players bring?", "What time is the game?"]; return ["What time should we arrive?", "Where is the game?"]; }
function deterministicAnswer(question: string, context: TeamContext): AiAnswer { const q = question.toLowerCase(); const game = context.game; const foundFaq = context.faqs.find((faq) => [faq.keyword, faq.question].filter(Boolean).some((v) => q.includes(String(v).toLowerCase()))); if (/\b(hi|hello|hey|thanks|thank you)\b/.test(q)) return { intents:["greeting"], answer:`Hi! I can help with ${context.teamName} game details like time, location, uniforms, parking, and what to bring.`, followups:["What time should we arrive?","What uniform should players wear?"], needsFollowup:false }; if (!game && !foundFaq) return { intents:["unknown"], answer:"Coach has not posted the next game details yet. Please check back soon or ask the coach to add them.", followups:["Has the next game been posted?","Who should I contact?"], needsFollowup:true };
  const parts:string[]=[]; const detected:AiAnswer["intents"]=[];
  if (/time|when|start/.test(q)) { detected.push("game_time"); if (game?.game_time) parts.push(`First pitch is ${game.game_time}.`); }
  if (/arriv|there|show up/.test(q)) { detected.push("arrival_time"); if (game?.arrival_time) parts.push(`Players should arrive by ${game.arrival_time}.`); }
  if (/date|day/.test(q)) { detected.push("game_date"); if (game?.game_date) parts.push(`The game is on ${game.game_date}.`); }
  if (/where|location|field|address|map|directions/.test(q)) { detected.push(q.includes("directions") || q.includes("map") ? "directions" : "game_location"); if (game?.location_name || game?.location_address) parts.push(`Location: ${[game.location_name, game.location_address].filter(Boolean).join(" - ")}${game.google_maps_url ? ` (${game.google_maps_url})` : ""}.`); }
  if (/park/.test(q)) { detected.push("parking"); if (game?.parking_notes) parts.push(`Parking: ${game.parking_notes}`); }
  if (/uniform|jersey|wear/.test(q)) { detected.push("uniform"); if (game?.uniform) parts.push(`Uniform: ${game.uniform}`); }
  if (/bring|equipment|water|snack/.test(q)) { detected.push("what_to_bring"); if (game?.what_to_bring) parts.push(`Bring: ${game.what_to_bring}`); }
  if (/opponent|playing|against/.test(q)) { detected.push("opponent"); if (game?.opponent) parts.push(`Opponent: ${game.opponent}.`); }
  if (/cancel|rain|weather/.test(q)) { detected.push(q.includes("weather") || q.includes("rain") ? "weather" : "cancellation"); if (game?.status) parts.push(`Current status: ${game.status}. Coach will post updates if anything changes.`); }
  if (foundFaq) { detected.push("faq_general"); parts.push(foundFaq.answer); }
  const answer = parts.length ? parts.join(" ") : "Coach has not posted that detail yet. Please check back later or ask the coach to add it."; return { intents: detected.length ? [...new Set(detected)] : ["unknown"], answer, followups: suggestFollowups(detected), needsFollowup: !parts.length };
}
export async function answerParentQuestion(question: string, context: TeamContext): Promise<AiAnswer> { if (!process.env.OPENAI_API_KEY) return deterministicAnswer(question, context); const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY }); const response = await client.responses.create({ model: process.env.OPENAI_MODEL || "gpt-4o-mini", input: [{ role:"system", content:"You answer youth sports parent questions for coaches. Use only supplied team data and FAQs. Never invent missing details. Keep answers short, friendly, and GroupMe-ready. Return strict JSON with intents, answer, followups, needsFollowup." }, { role:"user", content: JSON.stringify({ question, allowedIntents:intents, context }) }], text: { format: { type:"json_schema", name:"coach_answer", schema: { type:"object", additionalProperties:false, required:["intents","answer","followups","needsFollowup"], properties:{ intents:{ type:"array", items:{ type:"string", enum:intents } }, answer:{ type:"string" }, followups:{ type:"array", items:{ type:"string" }, maxItems:3 }, needsFollowup:{ type:"boolean" } } } } } }); const parsed = aiAnswerSchema.safeParse(JSON.parse(response.output_text)); return parsed.success ? parsed.data : deterministicAnswer(question, context); }
export function formatGroupMeAnswer(result: AiAnswer) { const followups = result.followups.length ? `\n\nYou can also ask: ${result.followups.map((f) => `"${f}"`).join(" or ")}` : ""; return `${result.answer}${followups}`; }
