import { z } from "zod";
const GROUPME_API = "https://api.groupme.com/v3";
const GROUPME_BOT_API = "https://api.groupme.com/v3/bots";
export const groupMePayloadSchema = z.object({ attachments: z.array(z.unknown()).optional(), avatar_url: z.string().nullable().optional(), created_at: z.number().optional(), group_id: z.string(), id: z.string().optional(), name: z.string().nullable().optional(), sender_id: z.string().nullable().optional(), sender_type: z.string().nullable().optional(), source_guid: z.string().optional(), system: z.boolean().optional(), text: z.string().nullable().optional(), user_id: z.string().nullable().optional() });
export type GroupMePayload = z.infer<typeof groupMePayloadSchema>;
export function validateIncomingGroupMePayload(payload: unknown) { return groupMePayloadSchema.safeParse(payload); }
export function shouldIgnoreGroupMeMessage(payload: GroupMePayload) { const text = payload.text?.trim(); return !text || payload.system || payload.sender_type === "bot" || payload.sender_type === "system"; }
export async function createGroupMeBot(accessToken: string, groupId: string, botName: string, callbackUrl: string) { const response = await fetch(`${GROUPME_API}/bots?token=${encodeURIComponent(accessToken)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bot: { name: botName, group_id: groupId, callback_url: callbackUrl } }) }); if (!response.ok) throw new Error(`GroupMe bot create failed: ${response.status} ${await response.text()}`); const json = await response.json(); return json.response.bot as { bot_id: string; group_id: string; name: string; callback_url?: string }; }
export async function postGroupMeMessage(botId: string, text: string) { const response = await fetch(`${GROUPME_BOT_API}/post`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bot_id: botId, text: text.slice(0, 950) }) }); if (!response.ok) throw new Error(`GroupMe post failed: ${response.status} ${await response.text()}`); return response.json().catch(() => ({})); }
export async function listGroupMeGroups(accessToken: string) { const response = await fetch(`${GROUPME_API}/groups?token=${encodeURIComponent(accessToken)}`); if (!response.ok) throw new Error(`GroupMe groups failed: ${response.status} ${await response.text()}`); const json = await response.json(); return json.response as Array<{ id: string; name: string }>; }
